FROM continuumio/anaconda3:2022.05
LABEL maintainer="sauloandrade"
run mkdir -p /opt/fds
run git clone https://github.com/sauloaalmeida/FundamentosDataScience.git /opt/fds
run conda install jupyter -y --quiet
